
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FREETYPE_VERSION: 2.13.2

jobs:
  download-deps:
    name: Download dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Check FreeType
      id: cache-freetype-src
      uses: actions/cache@v3
      with:
        path: freetype-${{ env.FREETYPE_VERSION }}.tar.gz
        key: freetype-${{ env.FREETYPE_VERSION }}-source

    - name: Download FreeType
      if: steps.cache-freetype-src.output.cache-hit != 'true'
      run: curl -L -o freetype-${FREETYPE_VERSION}.tar.gz https://sourceforge.net/projects/freetype/files/freetype2/${FREETYPE_VERSION}/freetype-${FREETYPE_VERSION}.tar.gz/download

  windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
        - { name: x86, flags: -A Win32 }
        - { name: x64, flags: -A x64 }
        build: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3

    - name: "CMake: Configure"
      run: cmake -B build ${{ matrix.arch.flags }}

    - name: "CMake: Build"
      run: cmake --build build --config ${{ matrix.build }}

    - name: "CMake: Install"
      run: cmake --install build --config ${{ matrix.build }} --prefix install

    - uses: actions/upload-artifact@v3
      with:
        name: tyhylge-windows-${{ matrix.arch.name }}-${{ matrix.build }}
        path: install/*

  build-linux-deps:
    name: Linux (Build dependencies)
    runs-on: ubuntu-latest
    needs: download-deps
    container:
      image: centos:7

    steps:
    - name: Install system dependencies
      run: yum install -y make gcc gcc-c++

    - name: "FreeType: binary cache"
      id: cache-freetype
      uses: actions/cache@v3
      with:
        path: freetype-build
        key: ${{ runner.os }}-freetype-${{ env.FREETYPE_VERSION }}

    - name: "FreeType: source cache"
      if: steps.cache-freetype.output.cache-hit != 'true'
      uses: actions/cache/restore@v3
      with:
        path: freetype-${{ env.FREETYPE_VERSION }}.tar.gz
        key: freetype-${{ env.FREETYPE_VERSION }}-source

    - name: "FreeType: build"
      if: steps.cache-freetype.output.cache-hit != 'true'
      run: |
        curl -L -o freetype-${FREETYPE_VERSION}.tar.gz https://sourceforge.net/projects/freetype/files/freetype2/${FREETYPE_VERSION}/freetype-${FREETYPE_VERSION}.tar.gz/download
        tar xf freetype-${FREETYPE_VERSION}.tar.gz
        cd freetype-${FREETYPE_VERSION}
        ./configure --prefix=${GITHUB_WORKSPACE}/freetype-build
        make -j4
        make install

  linux:
    name: Linux
    runs-on: ubuntu-latest
    needs: build-linux-deps
    container:
      image: centos:7
    env:
      CMAKE_VERSION: 3.28.1

    strategy:
      matrix:
        build: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3

    - name: "Dependency: FreeType"
      uses: actions/cache/restore@v3
      with:
        path: freetype-build
        key: ${{ runner.os }}-freetype-${{ env.FREETYPE_VERSION }}

    - name: "Cache CMake ${{ env.CMAKE_VERSION }}"
      id: cache-cmake
      uses: actions/cache@v3
      with:
        path: cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.sh
        key: ${{ runner.os }}-cmake-${{ env.CMAKE_VERSION }}

    - name: "Download CMake ${{ env.CMAKE_VERSION }}"
      if: steps.cache-cmake.outputs.cache-hit != 'true'
      run: |
        curl -L -O https://cmake.org/files/v3.28/cmake-${CMAKE_VERSION}-linux-x86_64.sh
        chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh

    - name: "Install CMake ${{ env.CMAKE_VERSION }}"
      run: ./cmake-${CMAKE_VERSION}-linux-x86_64.sh --prefix=/usr/local --skip-license

    - name: "CMake: Configure"
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build }}
        -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/freetype-build
        -DTYHYLGE_USE_FREETYPE=1

    - name: "CMake: Build"
      run: cmake --build build

    - name: "CMake: Install"
      run: cmake --install build --prefix install

    - uses: actions/upload-artifact@v3
      with:
        name: tyhylge-linux-amd64-${{ matrix.build }}
        path: install/*

